repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        exclude: "^(.direnv/|.*year201[89])"
        types: [python]
  - repo: https://github.com/ambv/black
    rev: 25.1.0
    hooks:
      - id: black
        exclude: ^.direnv/
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        exclude: ^.direnv/
