[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[tool.black]
line_length = 88

[tool.pylint.messages_control]
disable = """
bad-continuation,
bad-whitespace,
duplicate-code,
invalid-name,
missing-class-docstring,
missing-function-docstring,
missing-module-docstring,
"""
ignore = "year2018, year2019"

[tool.pylint.master]
ignore = "year2018, year2019"
jobs = 0

[tool.pylint.format]
max-line-length = "88"
