[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[tool.black]
line_length = 88
target_version = ["py311"]

[tool.mypy]
strict_optional = false

[[tool.mypy.overrides]]
module = [
    "anytree",
    "aocd",
    "aocd.models",
    "networkx",
]
ignore_missing_imports = true

[tool.pylint.messages_control]
disable = """
duplicate-code,
invalid-name,
missing-class-docstring,
missing-function-docstring,
missing-module-docstring,
too-few-public-methods
"""
ignore = "year2018, year2019"

[tool.pylint.master]
ignore = "year2018, year2019"
jobs = 0

[tool.pylint.format]
max-line-length = "88"
