name: pytest
on:
  push:
    branches: ['*']
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: install requirements
        run: pip install -r requirements.txt
      - name: run tests
        env:
          AOC_SESSION: ${{ secrets.AOC_SESSION }}
        run: pytest --cov=./ --cov-report=xml --mypy --pylint --pylint-ignore-patterns '.*year201[89].*'
      - name: upload code coverage
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
          verbose: true
